---
- hosts: all
  roles:
   - role: "{{ playbook_dir }}"
     minecraft_version: 1.13.1
     minecraft_eula_accept: "{{user_accept_minecraft_eula}}"
     minecraft_server_properties:
       server-port: 25565
       rcon.port: 25564
       enable-rcon: true
       rcon.password: password
