---

- name: load system specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- name: install java dependency
  include: java/prepare_java_dependencies.yml
  when: not minecraft_java_external_managed

- name: install spigot package
  package:
    name: "{{ item }}"
  register: pack_res
  retries: 5
  until: pack_res is success
  with_items: "{{ dependencies_spigot }}"
  when: minecraft_server == 'spigot'

- name: create Minecraft group
  group:
    state: present
    name: "{{ minecraft_group }}"
    system: true

- name: create Minecraft user
  user:
    state: present
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    system: true

- name: set executable name (Minecraft)
  set_fact:
    minecraft_jar: minecraft_server.jar
  when: minecraft_server == 'minecraft'

- name: set executable name (Spigot)
  set_fact:
    minecraft_jar: spigot.jar
  when: minecraft_server == 'spigot'
