- include: minecraft.yml
  when: minecraft_server == 'minecraft'

- include: spigot.yml
  when: minecraft_server == 'spigot'

- name: agree to EULA
  template:
    src: eula.txt.j2
    dest: "{{ deploy_helper.shared_path }}/eula.txt"
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service
