---

- include: minecraft.yml
  when: minecraft_server == 'minecraft'

- include: spigot.yml
  when: minecraft_server == 'spigot'

- name: agree to EULA
  lineinfile:
    dest: "{{ deploy_helper.shared_path }}/eula.txt"
    regexp: '^eula='
    line: 'eula={{ minecraft_eula_accept | lower }}'
    create: true
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service
