- name: "compare current os version with supported versions"
  set_fact:
    supported_version: "{{ansible_distribution_major_version is version('7', '>=')}}"

- name: check supported version
  fail:
    msg: "Using Supervisor with {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported. Use systemd instead."
  when: supported_version

- name: install Supervisor
  yum:
    name: supervisor
