---
- name: update whitelist
  minecraft_server_file:
    server_file: whitelist
    values: "{{ minecraft_whitelist }}"
    path: "{{ deploy_helper.shared_path }}/whitelist.json"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
  when: minecraft_whitelist | length > 0

- name: update ops
  minecraft_server_file:
    server_file: ops
    values: "{{ minecraft_ops }}"
    path: "{{ deploy_helper.shared_path }}/ops.json"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
  when: minecraft_ops | length > 0

- name: update banned-players
  minecraft_server_file:
    server_file: banned-players
    values: "{{ minecraft_banned_players }}"
    path: "{{ deploy_helper.shared_path }}/banned-players.json"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
  when: minecraft_banned_players | length > 0

- name: update banned-ips
  minecraft_server_file:
    server_file: banned-ips
    values: "{{ minecraft_banned_ips }}"
    path: "{{ deploy_helper.shared_path }}/banned-ips.json"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
  when: minecraft_banned_ips | length > 0
