- name: "init initial server.properties from templates"
  template:
    src: "server.properties.j2"
    dest: "{{ minecraft_home }}/server.properties"
    force: false
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- name: update server.properties
  minecraft_server_file:
    server_file: server-properties
    values: "{{ minecraft_server_properties }}"
    path: "{{ minecraft_home }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
