---
- name: check for supported OS
  assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: check for supported server implementation
  assert:
    that:
      - "minecraft_server in supported_minecraft_servers"

- include: "{{ minecraft_hook_before_setup | default('empty.yml') }}"

- include: fetchversion/main.yml

- include: setup/main.yml

- include: plugins/main.yml
  when: "minecraft_plugin_sets is defined and (0 < minecraft_plugin_sets | length )"

- include: "{{ minecraft_hook_after_setup | default('empty.yml') }}"

- include: "{{ minecraft_hook_before_download | default('empty.yml') }}"

- include: downloadhelper/main.yml

- include: download/main.yml

- include: "{{ minecraft_hook_after_download | default('empty.yml') }}"

- include: "{{ minecraft_hook_before_install | default('empty.yml') }}"

- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ minecraft_home }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize

- include: install/main.yml

- include: "{{ minecraft_hook_after_install | default('empty.yml') }}"

- include: acl.yml

- include: configure.yml

- include: setup/supervisor.yml
  when: minecraft_process_control == 'supervisor'

- include: setup/systemd.yml
  when: minecraft_process_control == 'systemd'

- include: "{{ minecraft_hook_before_start | default('empty.yml') }}"

- meta: flush_handlers

- include: "{{ minecraft_hook_after_start | default('empty.yml') }}"
