---
- name: load version informations
  uri:
    url: "{{ minecraft_version_manifest_url }}"
    return_content: true
  register: minecraft_versions

- name: find latest release version
  set_fact:
    minecraft_version: "{{ minecraft_versions.json.latest.release }}"
  when: minecraft_version == "latest"

- name: extract version specific mainfest file
  set_fact:
    minecraft_version_manifest_url: "{{ item.url }}"
  when: item.id == (minecraft_version|string)
  with_items: "{{ minecraft_versions.json.versions }}"

- name: Download the version specific mainfest file
  uri:
    url: "{{ minecraft_version_manifest_url }}"
    return_content: true
  register: minecraft_version_info

- name: "extract the download url from version manifest"
  set_fact:
    minecraft_server_download_url: "{{ minecraft_version_info.json.downloads.server.url }}"
    minecraft_server_download_checksum: "sha1:{{ minecraft_version_info.json.downloads.server.sha1 }}"
