---
- name: load version informations
  uri:
    url: "{{ minecraft_version_manifest_url }}"
    return_content: true
  register: minecraft_versions

- name: find latest release version
  set_fact:
    minecraft_version_int: "{{ minecraft_versions.json.latest.release }}"
  when: minecraft_version == "latest"

- name: find latest release version
  set_fact:
    minecraft_version_int: "{{ minecraft_version }}"
  when: minecraft_version != "latest"

- name: find latest release version
  set_fact:
    minecraft_version_download_manifest_url: "{{ minecraft_versions.json.versions
      | selectattr('id', 'eq', (minecraft_version_int|string) )
      | map(attribute='url')
      | list
      | first }}"

- name: show located minecraft version
  debug:
    msg: "Download {{ minecraft_version_int }} from {{ minecraft_version_download_manifest_url }}"

- name: Download the version specific mainfest file
  uri:
    url: "{{ minecraft_version_download_manifest_url }}"
    return_content: true
  register: minecraft_version_info

- name: "extract the download url from version manifest"
  set_fact:
    minecraft_server_download_url: "{{ minecraft_version_info.json.downloads.server.url }}"
    minecraft_server_download_checksum: "sha1:{{ minecraft_version_info.json.downloads.server.sha1 }}"
  no_log: true
