- name: install jessie-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
  when: ansible_distribution_release == 'jessie'


- name: Install Java by apt for debian jessie
  apt:
    name: "{{ java_package_name }}"
    state: present
    install_recommends: true
    default_release: "{{ (ansible_distribution_release == 'jessie') | ternary('jessie-backports', omit) }}"
  register: apt_res
  retries: 5
  until: apt_res is success
  when: ansible_distribution_release == 'jessie'
