---

- debug: msg="CX {{ ansible_distribution_release }} {{ ansible_distribution }} {{ ansible_os_family }}"

- name: install java package
  package:
    name: "{{ java_package_name }}"
  register: pack_res
  retries: 5
  until: pack_res is success
