---
- name: check supported version
  fail:
    msg: <
      Using Supervisor with {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported.
      Use systemd instead.
  when: ansible_distribution_major_version is version('7', '>=')

- name: install Supervisor
  yum:
    name: supervisor
  register: pack_res
  retries: 5
  until: pack_res is success
