---
- hosts: localhost
  connection: local
  tasks:

    - set_fact:
        test: "Multiverse-SignPortals-3.0.0-SNAPSHOT.jar"
        artefacts:
          - fileName: "Multiverse-SignPortals-3.0.0-SNAPSHOT-javadoc.jar"
          - fileName: "Multiverse-SignPortals-3.0.0-SNAPSHOT-sources.jar"
          - fileName: "Multiverse-SignPortals-3.0.0-SNAPSHOT.jar"


    #- debug: msg="{{ test is not search('-sources.jar') }}"
    - set_fact:
        filterd: "{{ artefacts | selectattr('fileName', 'match', '(^((?!sources).)*$)') | list | selectattr('fileName', 'match', '(^((?!javadoc).)*$)') | list | map(attribute='fileName') | list  }}"
    - debug: var=filterd
    - debug: msg="{{ artefacts | selectattr('fileName', 'match', '(^((?!sources).)*$)') | list | selectattr('fileName', 'match', '(^((?!javadoc).)*$)') | list | map(attribute='fileName') | list  }}"

    #- debug: msg="{{ artefacts | map(attribute='fileName') | list | search('-sources.jar') }}"

#    - set_fact:
#        plugin_download_src: "/artifact/target/{{ artefact.fileName }}"
#      when:
#        (artefact.fileName is not search('-sources.jar')) == false and
#        (artefact.fileName is not search('-javadoc.jar')) == false
#      with_items: artefacts
#      loop_control:
#        loop_var: artefact

  #  - debug: var=plugin_download_src
